### ISSUE TITLE
sbin missing from PATH

### ISSUE THREAD

**Issue by Cloudef** [urjaman/dchrt-ng#2]
It seems `/etc/profile` appends `sbin` only if `root`. While `sbin` is documented only for essential binaries for system restore, stuff like xmllint gets installed there and used by makepnd to validate procuded PNDs. I think there is some weird debian policy for whether `sbin` is or is not in PATH that angstrom inherits. 

Solutions are: 1) repackage libxml2-utils to install them to bin 2) add sbin to PATH 3) append sbin to PATH in makepnd

**Comment by urjaman** [comment]
I'll pick (3) for now, as thats how the pandora runs too... This is actually a bit of a side effect of apparently we dont ever run the /etc/profile or ~/.profile (this one has the pandora $PATH) things since i just launch a dropbear (that /usr/bin:/bin is the dropbear default path) and for some reason those logins arent a login shell so all that is run is ~/.bashrc but i'm lazy so i just made the scripts add it to .bashrc along with a few other helpful things (LANG, and default the container to . ngcc-x64 )
