### ISSUE TITLE
Container fails with error code 1

### ISSUE THREAD

**Issue by ScaroDj** [urjaman/dchrt-ng#4]
Hello Urjaman, 

I'm trying to create a container inside a VBox with Debian Jessie and KDE up to date at the moment of writing. 

I faced the following issues:
1. http://ftp.debian.org/debian/pool/main/q/qemu/qemu-user-static_2.8+dfsg-6_amd64.deb is no longer available, so I downloaded a similar package from a Debian mirror named qemu-user-static_2.8+dfsg-6+deb9u5_amd64.deb from which I extracted the qemu-arm-static as the code in make-dchrt-ng.sh suggests. 

2. At this point I had a problem with nspawn not existing in my system for which I installed systemd-container. 

3. Now I'm at an impasse with the following output:
`scarodj@debian64:~/codez/dchrt-ng$ ./make-container.sh
+ '[' '!' -f pandora-xfce-image-omap3-pandora.tar.bz2 ']'
+ '[' '!' -d dchrt-ng ']'
+ '[' '!' -f dchrt-ng/usr/bin/qemu-arm-static ']'
+ sudo ./nspawn-install.sh
[sudo] password for scarodj: 
cp: cannot stat 'bolt-on/qemu-arm-static.conf': No such file or directory
Installed /etc/binfmt.d/qemu-arm-static.conf
Spawning container dchrt-ng-inst on /home/scarodj/codez/dchrt-ng/dchrt-ng.
Press ^] three times within 1s to kill container.
execv(/inst/run.sh) failed: Exec format error
Container dchrt-ng-inst failed with error code 1.
`

Thanks in advance if any help is possible at this point in Pandora's history.

**Comment by urjaman** [comment]
>  cp: cannot stat 'bolt-on/qemu-arm-static.conf': No such file or directory

There's your likely issue of my causing (tho it shouldnt be that hard to look around a repo for a file... hey i had to do that, i didnt know where i had moved it :P) since i apparently had not even tried this after shuffling things around. I committed a guess of a fix so if you want to pull that and try you can.

But yeah umm as you can see i havent touched this in a couple of years, things bitrot so I still dont know if it'll work without some love & care (also, the only distro it has been tested on is arch... back in 2017).
